import os

# Erweiterte Mapping-Liste für 1.8.8 → 1.21.4, inkl. Netzwerk/Server-Kommunikation
REPLACEMENTS = {
    # --- Vanilla Minecraft Imports ---
    "import net.minecraft.client.entity.PlayerSP;": "import net.minecraft.client.player.LocalPlayer;",
    "import net.minecraft.entity.player.PlayerMP;": "import net.minecraft.server.level.ServerPlayer;",
    "import net.minecraft.entity.player.EntityPlayer;": "import net.minecraft.world.entity.player.Player;",
    "import net.minecraft.entity.player.Player;": "import net.minecraft.world.entity.player.Player;",
    "import net.minecraft.client.multiplayer.WorldClient;": "import net.minecraft.client.multiplayer.ClientLevel;",
    "import net.minecraft.client.multiplayer.LevelClient;": "import net.minecraft.client.multiplayer.ClientLevel;",
    "import net.minecraft.world.WorldServer;": "import net.minecraft.server.level.ServerLevel;",
    "import net.minecraft.world.demo.DemoWorldServer;": "import net.minecraft.server.level.DemoLevel;",
    "import net.minecraft.world.demo.DemoLevelServer;": "import net.minecraft.server.level.DemoLevel;",
    "import net.minecraft.world.WorldType;": "import net.minecraft.world.level.levelgen.WorldGenSettings;",
    "import net.minecraft.world.LevelType;": "import net.minecraft.world.level.levelgen.WorldGenSettings;",
    "import net.minecraft.world.WorldSettings;": "import net.minecraft.world.level.LevelSettings;",
    "import net.minecraft.world.LevelSettings;": "import net.minecraft.world.level.LevelSettings;",
    "import net.minecraft.world.storage.WorldInfo;": "import net.minecraft.world.level.storage.LevelData;",
    "import net.minecraft.world.storage.LevelInfo;": "import net.minecraft.world.level.storage.LevelData;",
    "import net.minecraft.world.storage.SaveFormatOld;": "import net.minecraft.world.level.storage.LevelStorageSource;",
    "import net.minecraft.world.storage.SaveFormatComparator;": "import net.minecraft.world.level.storage.LevelSummary;",
    "import net.minecraft.world.storage.ISaveHandler;": "import net.minecraft.world.level.storage.LevelStorageSource.LevelStorageAccess;",
    "import net.minecraft.world.storage.IPlayerFileData;": "import net.minecraft.world.level.storage.PlayerDataStorage;",
    "import net.minecraft.world.storage.ThreadedFileIOBase;": "import net.minecraft.world.level.storage.io.ThreadedFileIoQueue;",
    "import net.minecraft.client.gui.GuiMainMenu;": "import net.minecraft.client.gui.screens.TitleScreen;",
    "import net.minecraft.client.gui.GuiChat;": "import net.minecraft.client.gui.screens.ChatScreen;",
    "import net.minecraft.client.gui.GuiDisconnected;": "import net.minecraft.client.gui.screens.DisconnectedScreen;",
    "import net.minecraft.client.gui.GuiMultiplayer;": "import net.minecraft.client.gui.screens.multiplayer.JoinMultiplayerScreen;",
    "import net.minecraft.client.gui.ScreenServerList;": "import net.minecraft.client.gui.screens.multiplayer.ServerListScreen;",
    "import net.minecraft.client.gui.GuiCreateWorld;": "import net.minecraft.client.gui.screens.worldselection.CreateWorldScreen;",
    "import net.minecraft.client.gui.GuiCreateLevel;": "import net.minecraft.client.gui.screens.worldselection.CreateWorldScreen;",
    "import net.minecraft.client.gui.GuiSelectWorld;": "import net.minecraft.client.gui.screens.worldselection.SelectWorldScreen;",
    "import net.minecraft.client.gui.GuiSelectLevel;": "import net.minecraft.client.gui.screens.worldselection.SelectWorldScreen;",
    "import net.minecraft.client.gui.GuiRenameWorld;": "import net.minecraft.client.gui.screens.worldselection.EditWorldScreen;",
    "import net.minecraft.client.gui.GuiRenameLevel;": "import net.minecraft.client.gui.screens.worldselection.EditWorldScreen;",
    "import net.minecraft.client.gui.GuiYesNo;": "import net.minecraft.client.gui.screens.ConfirmScreen;",
    "import net.minecraft.client.gui.GuiSlot;": "import net.minecraft.client.gui.components.ContainerObjectSelectionList;",
    "import net.minecraft.client.gui.GuiTextField;": "import net.minecraft.client.gui.components.EditBox;",
    "import net.minecraft.client.gui.ScaledResolution;": "import net.minecraft.client.gui.GuiGraphics;",  # Kein direkter Ersatz, ggf. im Code anpassen
    "import net.minecraft.client.audio.SoundHandler;": "import net.minecraft.client.sounds.SoundManager;",
    "import net.minecraft.client.audio.SoundCategory;": "import net.minecraft.sounds.SoundSource;",
    "import net.minecraft.client.audio.SoundPoolEntry;": "import net.minecraft.client.sounds.Sound;",
    "import net.minecraft.client.audio.ISound;": "import net.minecraft.client.sounds.SoundInstance;",
    "import net.minecraft.client.audio.ITickableSound;": "import net.minecraft.client.sounds.TickableSoundInstance;",
    "import net.minecraft.client.audio.ISound.AttenuationType;": "import net.minecraft.client.sounds.SoundInstance.Attenuation;",
    "import net.minecraft.client.audio.SoundEventAccessorComposite;": "import net.minecraft.client.sounds.SoundEventListener;",
    "import net.minecraft.client.audio.PositionedSoundRecord;": "import net.minecraft.client.sounds.WeighedSoundEvents;",
    "import net.minecraft.client.LoadingScreenRenderer;": "import net.minecraft.client.gui.screens.LoadingOverlay;",
    "import net.minecraft.util.ChatComponentText;": "import net.minecraft.network.chat.TextComponent;",
    "import net.minecraft.util.ChatComponentTranslation;": "import net.minecraft.network.chat.TranslatableComponent;",
    "import net.minecraft.util.IChatComponent;": "import net.minecraft.network.chat.Component;",
    "import net.minecraft.util.ReportedException;": "import net.minecraft.CrashReport;",
    "import net.minecraft.util.StringTranslate;": "import net.minecraft.locale.Language;",
    "import net.minecraft.util.ITickable;": "import net.minecraft.world.level.block.entity.TickableBlockEntity;",
    "import net.minecraft.util.Util;": "import net.minecraft.util.Mth;",
    "import net.minecraft.init.Bootstrap;": "import net.minecraft.SharedConstants;",
    "import net.minecraft.nbt.NBTTagCompound;": "import net.minecraft.nbt.CompoundTag;",
    "import net.minecraft.nbt.NBTTagList;": "import net.minecraft.nbt.ListTag;",
    "import net.minecraft.nbt.CompressedStreamTools;": "import net.minecraft.nbt.NbtIo;",
    "import net.minecraft.network.EnumConnectionState;": "import net.minecraft.network.ConnectionProtocol;",
    "import net.minecraft.network.EnumPacketDirection;": "import net.minecraft.network.protocol.PacketFlow;",
    "import net.minecraft.network.Packet;": "import net.minecraft.network.protocol.Packet;",
    "import net.minecraft.network.PacketBuffer;": "import net.minecraft.network.FriendlyByteBuf;",
    "import net.minecraft.network.login.client.C00PacketLoginStart;": "import net.minecraft.network.protocol.login.ServerboundHelloPacket;",
    "import net.minecraft.network.login.server.S00PacketDisconnect;": "import net.minecraft.network.protocol.login.ClientboundLoginDisconnectPacket;",
    "import net.minecraft.network.login.server.S01PacketEncryptionRequest;": "import net.minecraft.network.protocol.login.ClientboundHelloPacket;",
    "import net.minecraft.network.login.server.S02PacketLoginSuccess;": "import net.minecraft.network.protocol.login.ClientboundGameProfilePacket;",
    "import net.minecraft.network.login.server.S03PacketEnableCompression;": "import net.minecraft.network.protocol.login.ClientboundLoginCompressionPacket;",
    "import net.minecraft.network.login.client.C01PacketEncryptionResponse;": "import net.minecraft.network.protocol/login.ServerboundKeyPacket;",
    "import net.minecraft.network.login.client.C02PacketLoginSuccess;": "import net.minecraft.network.protocol/login.ServerboundCustomQueryPacket;",
    "import net.minecraft.network.play.client.C00PacketKeepAlive;": "import net.minecraft.network.protocol.game.ServerboundKeepAlivePacket;",
    "import net.minecraft.network.play.server.S00PacketKeepAlive;": "import net.minecraft.network.protocol.game.ClientboundKeepAlivePacket;",
    "import net.minecraft.network.play.client.C01PacketChatMessage;": "import net.minecraft.network.protocol.game.ServerboundChatPacket;",
    "import net.minecraft.network.play.server.S02PacketChat;": "import net.minecraft.network.protocol.game.ClientboundChatPacket;",
    "import net.minecraft.network.play.client.C02PacketUseEntity;": "import net.minecraft.network.protocol.game.ServerboundInteractPacket;",
    "import net.minecraft.network.play.server.S03PacketTimeUpdate;": "import net.minecraft.network.protocol.game.ClientboundSetTimePacket;",
    "import net.minecraft.network.play.client.C03PacketPlayer;": "import net.minecraft.network.protocol.game.ServerboundMovePlayerPacket;",
    "import net.minecraft.network.play.server.S08PacketPlayerPosLook;": "import net.minecraft.network.protocol.game.ClientboundPlayerPositionPacket;",
    "import net.minecraft.network.play.client.C07PacketPlayerDigging;": "import net.minecraft.network.protocol.game.ServerboundPlayerActionPacket;",
    "import net.minecraft.network.play.server.S23PacketBlockChange;": "import net.minecraft.network.protocol.game.ClientboundBlockUpdatePacket;",
    "import net.minecraft.network.play.server.S24PacketBlockAction;": "import net.minecraft.network.protocol.game.ClientboundBlockEventPacket;",
    "import net.minecraft.network.play.server.S25PacketBlockBreakAnim;": "import net.minecraft.network.protocol.game.ClientboundBlockDestructionPacket;",
    "import net.minecraft.network.play.server.S26PacketMapChunkBulk;": "import net.minecraft.network.protocol.game.ClientboundChunksBiomesPacket;",
    "import net.minecraft.network.play.server.S27PacketExplosion;": "import net.minecraft.network.protocol.game.ClientboundExplodePacket;",
    "import net.minecraft.network.play.server.S28PacketEffect;": "import net.minecraft.network.protocol.game.ClientboundLevelEventPacket;",
    "import net.minecraft.network.play.server.S29PacketSoundEffect;": "import net.minecraft.network.protocol.game.ClientboundSoundPacket;",
    "import net.minecraft.network.play.server.S2APacketParticles;": "import net.minecraft.network.protocol.game.ClientboundLevelParticlesPacket;",
    "import net.minecraft.network.play.server.S2BPacketChangeGameState;": "import net.minecraft.network.protocol.game.ClientboundGameEventPacket;",
    "import net.minecraft.network.play.server.S2CPacketSpawnGlobalEntity;": "import net.minecraft.network.protocol.game.ClientboundAddGlobalEntityPacket;",
    "import net.minecraft.network.play.server.S2DPacketOpenWindow;": "import net.minecraft.network.protocol.game.ClientboundOpenScreenPacket;",
    "import net.minecraft.network.play.server.S2EPacketCloseWindow;": "import net.minecraft.network.protocol.game.ClientboundContainerClosePacket;",
    "import net.minecraft.network.play.server.S2FPacketSetSlot;": "import net.minecraft.network.protocol.game.ClientboundContainerSetSlotPacket;",
    "import net.minecraft.network.play.server.S30PacketWindowItems;": "import net.minecraft.network.protocol.game.ClientboundContainerSetContentPacket;",
    "import net.minecraft.network.play.server.S31PacketWindowProperty;": "import net.minecraft.network.protocol.game.ClientboundContainerSetDataPacket;",
    "import net.minecraft.network.play.server.S32PacketConfirmTransaction;": "import net.minecraft.network.protocol.game.ClientboundContainerAckPacket;",
    "import net.minecraft.network.play.server.S33PacketUpdateSign;": "import net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket;",
    "import net.minecraft.network.play.server.S34PacketMaps;": "import net.minecraft.network.protocol.game.ClientboundMapItemDataPacket;",
    "import net.minecraft.network.play.server.S35PacketUpdateTileEntity;": "import net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket;",
    "import net.minecraft.network.play.server.S36PacketSignEditorOpen;": "import net.minecraft.network.protocol.game.ClientboundOpenSignEditorPacket;",
    "import net.minecraft.network.play.server.S37PacketStatistics;": "import net.minecraft.network.protocol.game.ClientboundAwardStatsPacket;",
    "import net.minecraft.network.play.server.S38PacketPlayerListItem;": "import net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket;",
    "import net.minecraft.network.play.server.S39PacketPlayerAbilities;": "import net.minecraft.network.protocol.game.ClientboundPlayerAbilitiesPacket;",
    "import net.minecraft.network.play.server.S3APacketTabComplete;": "import net.minecraft.network.protocol.game.ClientboundTabListPacket;",
    "import net.minecraft.network.play.server.S3BPacketScoreboardObjective;": "import net.minecraft.network.protocol.game.ClientboundSetObjectivePacket;",
    "import net.minecraft.network.play.server.S3CPacketUpdateScore;": "import net.minecraft.network.protocol.game.ClientboundSetScorePacket;",
    "import net.minecraft.network.play.server.S3DPacketDisplayScoreboard;": "import net.minecraft.network.protocol.game.ClientboundSetDisplayObjectivePacket;",
    "import net.minecraft.network.play.server.S3EPacketTeams;": "import net.minecraft.network.protocol.game.ClientboundSetPlayerTeamPacket;",
    "import net.minecraft.network.play.server.S3FPacketCustomPayload;": "import net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket;",
    "import net.minecraft.network.play.server.S40PacketDisconnect;": "import net.minecraft.network.protocol.game.ClientboundDisconnectPacket;",
    "import net.minecraft.network.INetHandler;": "import net.minecraft.network.PacketListener;",
    "import net.minecraft.network.NetHandlerPlayServer;": "import net.minecraft.server.network.ServerGamePacketListenerImpl;",
    "import net.minecraft.network.NetHandlerPlayClient;": "import net.minecraft.client.multiplayer.ClientPacketListener;",
    "import net.minecraft.network.NetworkManager;": "import net.minecraft.network.Connection;",
    "import net.minecraft.network.PacketThreadUtil;": "import net.minecraft.network.PacketSendListener;",
    "import net.minecraft.network.ServerStatusResponse;": "import net.minecraft.network.protocol.status.ServerStatus;",
    "import net.minecraft.network.status.client.C00PacketServerQuery;": "import net.minecraft.network.protocol.status.ServerboundStatusRequestPacket;",
    "import net.minecraft.network.status.client.C01PacketPing;": "import net.minecraft.network.protocol.status.ServerboundPingRequestPacket;",
    "import net.minecraft.network.status.server.S00PacketServerInfo;": "import net.minecraft.network.protocol.status.ClientboundStatusResponsePacket;",
    "import net.minecraft.network.status.server.S01PacketPong;": "import net.minecraft.network.protocol.status.ClientboundPongResponsePacket;",
    "import net.minecraft.network.handshake.client.C00Handshake;": "import net.minecraft.network.protocol.handshake.ServerboundHelloPacket;",
    "import net.minecraft.network.EnumConnectionState;": "import net.minecraft.network.ConnectionProtocol;",
    "import net.minecraft.network.EnumPacketDirection;": "import net.minecraft.network.protocol.PacketFlow;",
    "import net.minecraft.network.Packet;": "import net.minecraft.network.protocol.Packet;",
    "import net.minecraft.network.PacketBuffer;": "import net.minecraft.network.FriendlyByteBuf;",
    "import net.minecraft.network.PacketListener;": "import net.minecraft.network.PacketListener;",
    "import net.minecraft.network.FriendlyByteBuf;": "import net.minecraft.network.FriendlyByteBuf;",
    "import net.minecraft.network.protocol.PacketFlow;": "import net.minecraft.network.protocol.PacketFlow;",
    "import net.minecraft.network.protocol.Packet;": "import net.minecraft.network.protocol.Packet;",
    "import net.minecraft.network.protocol.login.ServerboundHelloPacket;": "import net.minecraft.network.protocol.login.ServerboundHelloPacket;",
    "import net.minecraft.network.protocol.game.ServerboundKeepAlivePacket;": "import net.minecraft.network.protocol.game.ServerboundKeepAlivePacket;",
    "import net.minecraft.network.protocol.game.ClientboundKeepAlivePacket;": "import net.minecraft.network.protocol.game.ClientboundKeepAlivePacket;",
    "import net.minecraft.network.protocol.status.ServerboundStatusRequestPacket;": "import net.minecraft.network.protocol.status.ServerboundStatusRequestPacket;",
    "import net.minecraft.network.protocol.status.ServerboundPingRequestPacket;": "import net.minecraft.network.protocol.status.ServerboundPingRequestPacket;",
    "import net.minecraft.network.protocol.status.ClientboundStatusResponsePacket;": "import net.minecraft.network.protocol.status.ClientboundStatusResponsePacket;",
    "import net.minecraft.network.protocol.status.ClientboundPongResponsePacket;": "import net.minecraft.network.protocol.status.ClientboundPongResponsePacket;",
    "import net.minecraft.network.protocol.handshake.ServerboundHelloPacket;": "import net.minecraft.network.protocol.handshake.ServerboundHelloPacket;",
    "import net.minecraft.server.network.NetHandlerLoginServer;": "import net.minecraft.server.network.ServerLoginPacketListenerImpl;",
    "import net.minecraft.server.network.NetHandlerPlayServer;": "import net.minecraft.server.network.ServerGamePacketListenerImpl;",
    "import net.minecraft.server.network.ServerLoginPacketListenerImpl;": "import net.minecraft.server.network.ServerLoginPacketListenerImpl;",
    "import net.minecraft.server.network.ServerGamePacketListenerImpl;": "import net.minecraft.server.network.ServerGamePacketListenerImpl;",
    "import net.minecraft.client.multiplayer.ClientPacketListener;": "import net.minecraft.client.multiplayer.ClientPacketListener;",
    "import net.minecraft.network.Connection;": "import net.minecraft.network.Connection;",
    "import net.minecraft.network.PacketSendListener;": "import net.minecraft.network.PacketSendListener;",

    # --- Symbole (nur einfache, keine vollständigen Packagenamen!) ---
    "PlayerSP": "LocalPlayer",
    "PlayerMP": "ServerPlayer",
    "EntityPlayer": "Player",
    "DemoLevelServer": "DemoLevel",
    "DemoWorldServer": "DemoLevel",
    "LevelClient": "ClientLevel",
    "WorldClient": "ClientLevel",
    "WorldServer": "ServerLevel",
    "GuiTextField": "EditBox",
    "GuiMultiplayer": "JoinMultiplayerScreen",
    "ScreenServerList": "ServerListScreen",
    "GuiRenameLevel": "EditWorldScreen",
    "GuiYesNo": "ConfirmScreen",
    "GuiSlot": "ContainerObjectSelectionList",
    "GuiSelectLevel": "SelectWorldScreen",
    "GuiCreateLevel": "CreateWorldScreen",
    "GuiMainMenu": "TitleScreen",
    "GuiChat": "ChatScreen",
    "GuiDisconnected": "DisconnectedScreen",
    "LevelInfo": "LevelData",
    "WorldInfo": "LevelData",
    "LevelServer": "ServerLevel",
    "SaveFormatOld": "LevelStorageSource",
    "ISaveHandler": "LevelStorageSource.LevelStorageAccess",
    "SaveFormatComparator": "LevelSummary",
    "ReportedException": "CrashReport",
    "StringTranslate": "Language",
    "ITickable": "TickableBlockEntity",
    "SoundHandler": "SoundManager",
    "SoundCategory": "SoundSource",
    "ISound": "SoundInstance",
    "SoundPoolEntry": "Sound",
    "TickableSoundInstance": "TickableSoundInstance",
    "RenderSectionRegion": "SectionRenderDispatcher.RenderSectionRegion",
    "ScaledResolution": "GuiGraphics",
    "Util.EnumOS": "OperatingSystem",
    "C00PacketLoginStart": "ServerboundHelloPacket",
    "C01PacketEncryptionResponse": "ServerboundKeyPacket",
    "C02PacketLoginSuccess": "ServerboundCustomQueryPacket",
    "S00PacketDisconnect": "ClientboundLoginDisconnectPacket",
    "S01PacketEncryptionRequest": "ClientboundHelloPacket",
    "S02PacketLoginSuccess": "ClientboundGameProfilePacket",
    "S03PacketEnableCompression": "ClientboundLoginCompressionPacket",
    "C00PacketKeepAlive": "ServerboundKeepAlivePacket",
    "S00PacketKeepAlive": "ClientboundKeepAlivePacket",
    "C01PacketChatMessage": "ServerboundChatPacket",
    "S02PacketChat": "ClientboundChatPacket",
    "C02PacketUseEntity": "ServerboundInteractPacket",
    "S03PacketTimeUpdate": "ClientboundSetTimePacket",
    "C03PacketPlayer": "ServerboundMovePlayerPacket",
    "S08PacketPlayerPosLook": "ClientboundPlayerPositionPacket",
    "C07PacketPlayerDigging": "ServerboundPlayerActionPacket",
    "S23PacketBlockChange": "ClientboundBlockUpdatePacket",
    "S24PacketBlockAction": "ClientboundBlockEventPacket",
    "S25PacketBlockBreakAnim": "ClientboundBlockDestructionPacket",
    "S26PacketMapChunkBulk": "ClientboundChunksBiomesPacket",
    "S27PacketExplosion": "ClientboundExplodePacket",
    "S28PacketEffect": "ClientboundLevelEventPacket",
    "S29PacketSoundEffect": "ClientboundSoundPacket",
    "S2APacketParticles": "ClientboundLevelParticlesPacket",
    "S2BPacketChangeGameState": "ClientboundGameEventPacket",
    "S2CPacketSpawnGlobalEntity": "ClientboundAddGlobalEntityPacket",
    "S2DPacketOpenWindow": "ClientboundOpenScreenPacket",
    "S2EPacketCloseWindow": "ClientboundContainerClosePacket",
    "S2FPacketSetSlot": "ClientboundContainerSetSlotPacket",
    "S30PacketWindowItems": "ClientboundContainerSetContentPacket",
    "S31PacketWindowProperty": "ClientboundContainerSetDataPacket",
    "S32PacketConfirmTransaction": "ClientboundContainerAckPacket",
    "S33PacketUpdateSign": "ClientboundBlockEntityDataPacket",
    "S34PacketMaps": "ClientboundMapItemDataPacket",
    "S35PacketUpdateTileEntity": "ClientboundBlockEntityDataPacket",
    "S36PacketSignEditorOpen": "ClientboundOpenSignEditorPacket",
    "S37PacketStatistics": "ClientboundAwardStatsPacket",
    "S38PacketPlayerListItem": "ClientboundPlayerInfoUpdatePacket",
    "S39PacketPlayerAbilities": "ClientboundPlayerAbilitiesPacket",
    "S3APacketTabComplete": "ClientboundTabListPacket",
    "S3BPacketScoreboardObjective": "ClientboundSetObjectivePacket",
    "S3CPacketUpdateScore": "ClientboundSetScorePacket",
    "S3DPacketDisplayScoreboard": "ClientboundSetDisplayObjectivePacket",
    "S3EPacketTeams": "ClientboundSetPlayerTeamPacket",
    "S3FPacketCustomPayload": "ClientboundCustomPayloadPacket",
    "S40PacketDisconnect": "ClientboundDisconnectPacket",
    "NetHandlerPlayServer": "ServerGamePacketListenerImpl",
    "NetHandlerPlayClient": "ClientPacketListener",
    "NetworkManager": "Connection",
    "PacketThreadUtil": "PacketSendListener",
    "ServerStatusResponse": "ServerStatus",
    "C00PacketServerQuery": "ServerboundStatusRequestPacket",
    "C01PacketPing": "ServerboundPingRequestPacket",
    "S00PacketServerInfo": "ClientboundStatusResponsePacket",
    "S01PacketPong": "ClientboundPongResponsePacket",
    "C00Handshake": "ServerboundHelloPacket",
    "EnumConnectionState": "ConnectionProtocol",
    "EnumPacketDirection": "PacketFlow",
    "PacketBuffer": "FriendlyByteBuf",
    "ChatComponentText": "TextComponent",
    "ChatComponentTranslation": "TranslatableComponent",
    "IChatComponent": "Component",
    "INetHandler": "PacketListener",
    "NBTTagCompound": "CompoundTag",
    "NBTTagList": "ListTag",
    "CompressedStreamTools": "NbtIo",
    
}

REPLACEMENTS.update({
    # SoundManager und SoundMap (Eaglercraft → Vanilla)
    "import net.lax1dude.eaglercraft.v1_8.json.impl.SoundManager.SoundMapDeserializer;": "import net.minecraft.client.sounds.SoundManager.SoundMapDeserializer;",
    "SoundManager.SoundMap": "SoundManager.SoundMap",
    "SoundMapDeserializer": "SoundManager.SoundMapDeserializer",

    # Sound-Klassen
    "import net.minecraft.client.sounds.SoundInstance;": "import net.minecraft.client.sounds.SoundInstance;",
    "import net.minecraft.client.sounds.SoundInstance.Attenuation;": "import net.minecraft.client.sounds.SoundInstance.Attenuation;",
    "import net.minecraft.client.sounds.TickableSoundInstance;": "import net.minecraft.client.sounds.TickableSoundInstance;",
    "import net.minecraft.client.sounds.Sound;": "import net.minecraft.client.sounds.Sound;",
    "SoundInstance": "SoundInstance",
    "TickableSoundInstance": "TickableSoundInstance",
    "Sound": "Sound",
    "SoundSource": "SoundSource",

    # OperatingSystem
    "OperatingSystem": "net.minecraft.util.OperatingSystem",
    "import net.minecraft.util.OperatingSystem;": "import net.minecraft.util.OperatingSystem;",

    # TextComponent, TranslatableComponent
    "import net.minecraft.network.chat.TextComponent;": "import net.minecraft.network.chat.Component;",
    "import net.minecraft.network.chat.TranslatableComponent;": "import net.minecraft.network.chat.Component;",
    "TextComponent": "Component",
    "TranslatableComponent": "Component",

    # DemoLevel
    "import net.minecraft.server.level.DemoLevel;": "import net.minecraft.server.level.DemoLevel;",
    "DemoLevel": "DemoLevel",

    # Screen, ConfirmScreenCallback, Button
    "import net.minecraft.client.gui.screens.Screen;": "import net.minecraft.client.gui.screens.Screen;",
    "Screen": "Screen",
    "ConfirmScreenCallback": "net.minecraft.client.gui.screens.ConfirmScreen.Callback",
    "Button": "net.minecraft.client.gui.components.Button",

    # GameType
    "import net.minecraft.world.LevelSettings.GameType;": "import net.minecraft.world.level.GameType;",
    "GameType": "GameType",

    # LevelProvider
    "import net.minecraft.world.LevelProvider;": "import net.minecraft.world.level.LevelProvider;",
    "LevelProvider": "LevelProvider",

    # IChunkLoader, AnvilChunkLoader, Chunk, ChunkCoordIntPair, RegionFile
    "import net.minecraft.world.chunk.storage.IChunkLoader;": "import net.minecraft.world.level.chunk.storage.ChunkStorage;",
    "import net.minecraft.world.chunk.storage.AnvilChunkLoader;": "import net.minecraft.world.level.chunk.storage.ChunkStorage;",
    "import net.minecraft.world.chunk.storage.RegionFile;": "import net.minecraft.world.level.chunk.storage.RegionFile;",
    "import net.minecraft.world.chunk.Chunk;": "import net.minecraft.world.level.chunk.Chunk;",
    "import net.minecraft.world.ChunkCoordIntPair;": "import net.minecraft.world.level.ChunkPos;",
    "IChunkLoader": "ChunkStorage",
    "AnvilChunkLoader": "ChunkStorage",
    "Chunk": "Chunk",
    "ChunkCoordIntPair": "ChunkPos",
    "RegionFile": "RegionFile",

    # SaveHandler
    "import net.minecraft.world.storage.SaveHandler;": "import net.minecraft.world.level.storage.LevelStorageSource.LevelStorageAccess;",
    "SaveHandler": "LevelStorageSource.LevelStorageAccess",

    # ServerConfigurationManager
    "import net.minecraft.server.management.ServerConfigurationManager;": "import net.minecraft.server.players.PlayerList;",
    "ServerConfigurationManager": "PlayerList",

    # PacketListenerHandshakeServer, ServerboundHelloPacket
    "import net.minecraft.network.handshake.PacketListenerHandshakeServer;": "import net.minecraft.network.protocol.handshake.ServerHandshakePacketListener;",
    "import net.minecraft.network.handshake.client.ServerboundHelloPacket;": "import net.minecraft.network.protocol.handshake.ServerboundHelloPacket;",
    "PacketListenerHandshakeServer": "ServerHandshakePacketListener",
    "ServerboundHelloPacket": "ServerboundHelloPacket",

    # ServerGamePacketListenerImpl
    "import net.minecraft.network.ServerGamePacketListenerImpl;": "import net.minecraft.server.network.ServerGamePacketListenerImpl;",
    "ServerGamePacketListenerImpl": "ServerGamePacketListenerImpl",

    # BiomeGenBase, GenLayer, IntCache
    "import net.minecraft.world.biome.BiomeGenBase;": "import net.minecraft.world.level.biome.Biome;",
    "import net.minecraft.world.gen.layer.GenLayer;": "import net.minecraft.world.level.biome.layers.BiomeLayer;",
    "import net.minecraft.world.gen.layer.IntCache;": "import net.minecraft.world.level.biome.layers.IntCache;",
    "BiomeGenBase": "Biome",
    "GenLayer": "BiomeLayer",
    "IntCache": "IntCache",

    # CommandBase, CommandException, ICommandSender
    "import net.minecraft.command.CommandBase;": "import net.minecraft.commands.Command;",
    "import net.minecraft.command.CommandException;": "import net.minecraft.commands.CommandRuntimeException;",
    "import net.minecraft.command.ICommandSender;": "import net.minecraft.commands.CommandSourceStack;",
    "CommandBase": "Command",
    "CommandException": "CommandRuntimeException",
    "ICommandSender": "CommandSourceStack",

    # NBTTagString
    "import net.minecraft.nbt.NBTTagString;": "import net.minecraft.nbt.StringTag;",
    "NBTTagString": "StringTag",

    # Items, ItemStack
    "import net.minecraft.init.Items;": "import net.minecraft.world.item.Items;",
    "import net.minecraft.item.ItemStack;": "import net.minecraft.world.item.ItemStack;",
    "Items": "Items",
    "ItemStack": "ItemStack",

    # TickableBlockEntity
    "import net.minecraft.world.level.block.entity.TickableBlockEntity;": "import net.minecraft.world.level.block.entity.BlockEntityTicker;",
    "TickableBlockEntity": "BlockEntityTicker",

    # ClientPacketListener
    "import net.minecraft.client.network.ClientPacketListener;": "import net.minecraft.client.multiplayer.ClientPacketListener;",
    "ClientPacketListener": "ClientPacketListener",

    # PacketListenerLoginClient, ClientboundLoginDisconnectPacket
    "import net.minecraft.network.login.PacketListenerLoginClient;": "import net.minecraft.network.protocol.login.ClientLoginPacketListener;",
    "import net.minecraft.network.login.server.ClientboundLoginDisconnectPacket;": "import net.minecraft.network.protocol.login.ClientboundLoginDisconnectPacket;",
    "PacketListenerLoginClient": "ClientLoginPacketListener",
    "ClientboundLoginDisconnectPacket": "ClientboundLoginDisconnectPacket",
})

REPLACEMENTS.update({
    # Imports
    'import net.minecraft.block.state.IBlockState;': 'import net.minecraft.world.level.block.state.BlockState;',
    'import net.minecraft.init.Blocks;': 'import net.minecraft.world.level.block.Blocks;',
    'import net.minecraft.util.EnumFacing;': 'import net.minecraft.core.Direction;',
    'import net.minecraft.util.BlockPos;': 'import net.minecraft.core.BlockPos;',
    'import net.minecraft.util.MathHelper;': 'import net.minecraft.util.Mth;',
    'import net.minecraft.entity.Entity;': 'import net.minecraft.world.entity.Entity;',
    'import net.minecraft.world.World;': 'import net.minecraft.world.level.Level;',
    'import net.minecraft.client.resources.I18n;': 'import net.minecraft.client.resources.language.I18n;',
    'import net.minecraft.util.EnumChatFormatting;': 'import net.minecraft.ChatFormatting;',
    'import net.minecraft.util.ResourceLocation;': 'import net.minecraft.resources.ResourceLocation;',
    'import net.minecraft.client.gui.GuiButton;': 'import net.minecraft.client.gui.components.Button;',
    'import net.minecraft.client.gui.GuiScreen;': 'import net.minecraft.client.gui.screens.Screen;',
    'import net.minecraft.client.gui.FontRenderer;': 'import net.minecraft.client.gui.Font;',
    'import net.minecraft.client.renderer.Tessellator;': 'import com.mojang.blaze3d.vertex.Tesselator;',
    # Klassen-/Typnamen
    'IBlockState': 'BlockState',
    'EnumFacing': 'Direction',
    'BlockPos': 'BlockPos',
    'MathHelper': 'Mth',
    'EntityFX': 'Particle',
    'Entity': 'Entity',
    'World': 'Level',
    'EnumChatFormatting': 'ChatFormatting',
    'ResourceLocation': 'ResourceLocation',
    'GuiButton': 'Button',
    'GuiScreen': 'Screen',
    'FontRenderer': 'Font',
    'Tessellator': 'Tesselator',
    # Methoden
    'I18n.format': 'I18n.get',
    # Zusätzliche Imports und Typnamen
    'import net.minecraft.client.entity.EntityPlayerSP;': 'import net.minecraft.client.player.LocalPlayer;',
    'import net.minecraft.client.entity.AbstractClientPlayer;': 'import net.minecraft.client.player.AbstractClientPlayer;',
    'import net.minecraft.entity.player.EntityPlayer;': 'import net.minecraft.world.entity.player.Player;',
    'import net.minecraft.entity.player.InventoryPlayer;': 'import net.minecraft.world.entity.player.Inventory;',
    'import net.minecraft.entity.item.EntityItem;': 'import net.minecraft.world.entity.item.ItemEntity;',
    'import net.minecraft.entity.item.EntityXPOrb;': 'import net.minecraft.world.entity.ExperienceOrb;',
    'import net.minecraft.entity.monster.EntityMob;': 'import net.minecraft.world.entity.Mob;',
    'import net.minecraft.entity.passive.EntityAnimal;': 'import net.minecraft.world.entity.animal.Animal;',
    'import net.minecraft.entity.boss.EntityDragon;': 'import net.minecraft.world.entity.boss.enderdragon.EnderDragon;',
    'import net.minecraft.entity.boss.EntityWither;': 'import net.minecraft.world.entity.boss.wither.WitherBoss;',
    'import net.minecraft.entity.projectile.EntityArrow;': 'import net.minecraft.world.entity.projectile.Arrow;',
    'import net.minecraft.entity.projectile.EntitySnowball;': 'import net.minecraft.world.entity.projectile.Snowball;',
    'import net.minecraft.entity.projectile.EntityPotion;': 'import net.minecraft.world.entity.projectile.ThrownPotion;',
    'import net.minecraft.entity.projectile.EntityEnderPearl;': 'import net.minecraft.world.entity.projectile.ThrownEnderpearl;',
    'import net.minecraft.entity.projectile.EntityFireball;': 'import net.minecraft.world.entity.projectile.AbstractHurtingProjectile;',
    'import net.minecraft.entity.projectile.EntitySmallFireball;': 'import net.minecraft.world.entity.projectile.SmallFireball;',
    'import net.minecraft.entity.projectile.EntityLargeFireball;': 'import net.minecraft.world.entity.projectile.LargeFireball;',
    'import net.minecraft.entity.projectile.EntityEgg;': 'import net.minecraft.world.entity.projectile.ThrownEgg;',
    'import net.minecraft.entity.projectile.EntityFishHook;': 'import net.minecraft.world.entity.projectile.FishingBobber;',
    'import net.minecraft.entity.item.EntityBoat;': 'import net.minecraft.world.entity.vehicle.Boat;',
    'import net.minecraft.entity.item.EntityMinecart;': 'import net.minecraft.world.entity.vehicle.AbstractMinecart;',
    'import net.minecraft.entity.item.EntityMinecartChest;': 'import net.minecraft.world.entity.vehicle.MinecartChest;',
    'import net.minecraft.entity.item.EntityMinecartFurnace;': 'import net.minecraft.world.entity.vehicle.MinecartFurnace;',
    'import net.minecraft.entity.item.EntityMinecartTNT;': 'import net.minecraft.world.entity.vehicle.MinecartTNT;',
    'import net.minecraft.entity.item.EntityMinecartHopper;': 'import net.minecraft.world.entity.vehicle.MinecartHopper;',
    'import net.minecraft.entity.item.EntityMinecartCommandBlock;': 'import net.minecraft.world.entity.vehicle.MinecartCommandBlock;',
    'import net.minecraft.entity.item.EntityArmorStand;': 'import net.minecraft.world.entity.decoration.ArmorStand;',
    'import net.minecraft.entity.item.EntityPainting;': 'import net.minecraft.world.entity.decoration.Painting;',
    'import net.minecraft.entity.item.EntityItemFrame;': 'import net.minecraft.world.entity.decoration.ItemFrame;',
    'import net.minecraft.entity.EntityLivingBase;': 'import net.minecraft.world.entity.LivingEntity;',
    'import net.minecraft.entity.EntityLiving;': 'import net.minecraft.world.entity.LivingEntity;',
    'import net.minecraft.entity.EntityCreature;': 'import net.minecraft.world.entity.PathfinderMob;',
    'import net.minecraft.entity.EntityAgeable;': 'import net.minecraft.world.entity.AgeableMob;',
    'import net.minecraft.entity.EntityTameable;': 'import net.minecraft.world.entity.TamableAnimal;',
    'import net.minecraft.entity.EntityAmbientCreature;': 'import net.minecraft.world.entity.AmbientCreature;',
    'import net.minecraft.entity.EntityWaterMob;': 'import net.minecraft.world.entity.WaterAnimal;',
    'import net.minecraft.entity.EntityFlying;': 'import net.minecraft.world.entity.FlyingMob;',
    'import net.minecraft.entity.EntitySlime;': 'import net.minecraft.world.entity.Mob;',
    'import net.minecraft.entity.EntityGolem;': 'import net.minecraft.world.entity.Golem;',
    'import net.minecraft.entity.EntityVillager;': 'import net.minecraft.world.entity.npc.Villager;',
    'import net.minecraft.entity.EntityIronGolem;': 'import net.minecraft.world.entity.animal.IronGolem;',
    'import net.minecraft.entity.EntitySnowman;': 'import net.minecraft.world.entity.animal.SnowGolem;',
    'import net.minecraft.entity.EntityBat;': 'import net.minecraft.world.entity.ambient.Bat;',
    'import net.minecraft.entity.EntitySquid;': 'import net.minecraft.world.entity.animal.Squid;',
    'import net.minecraft.entity.EntityWolf;': 'import net.minecraft.world.entity.animal.Wolf;',
    'import net.minecraft.entity.EntityOcelot;': 'import net.minecraft.world.entity.animal.Cat;',
    'import net.minecraft.entity.EntityHorse;': 'import net.minecraft.world.entity.animal.horse.Horse;',
    'import net.minecraft.entity.EntityRabbit;': 'import net.minecraft.world.entity.animal.Rabbit;',
    'import net.minecraft.entity.EntityChicken;': 'import net.minecraft.world.entity.animal.Chicken;',
    'import net.minecraft.entity.EntityCow;': 'import net.minecraft.world.entity.animal.Cow;',
    'import net.minecraft.entity.EntityPig;': 'import net.minecraft.world.entity.animal.Pig;',
    'import net.minecraft.entity.EntitySheep;': 'import net.minecraft.world.entity.animal.Sheep;',
    'import net.minecraft.entity.EntityMooshroom;': 'import net.minecraft.world.entity.animal.MushroomCow;',
    'import net.minecraft.entity.EntityParrot;': 'import net.minecraft.world.entity.animal.Parrot;',
    'import net.minecraft.entity.EntityFox;': 'import net.minecraft.world.entity.animal.Fox;',
    'import net.minecraft.entity.EntityBee;': 'import net.minecraft.world.entity.animal.Bee;',
    'import net.minecraft.entity.EntityGoat;': 'import net.minecraft.world.entity.animal.goat.Goat;',
    'import net.minecraft.entity.EntityPolarBear;': 'import net.minecraft.world.entity.animal.PolarBear;',
    'import net.minecraft.entity.EntityTurtle;': 'import net.minecraft.world.entity.animal.Turtle;',
    'import net.minecraft.entity.EntityCod;': 'import net.minecraft.world.entity.animal.Cod;',
    'import net.minecraft.entity.EntitySalmon;': 'import net.minecraft.world.entity.animal.Salmon;',
    'import net.minecraft.entity.EntityPufferfish;': 'import net.minecraft.world.entity.animal.Pufferfish;',
    'import net.minecraft.entity.EntityTropicalFish;': 'import net.minecraft.world.entity.animal.TropicalFish;',
    'import net.minecraft.entity.EntityDolphin;': 'import net.minecraft.world.entity.animal.Dolphin;',
    'import net.minecraft.entity.EntityGuardian;': 'import net.minecraft.world.entity.monster.Guardian;',
    'import net.minecraft.entity.EntityElderGuardian;': 'import net.minecraft.world.entity.monster.ElderGuardian;',
    'import net.minecraft.entity.EntityShulker;': 'import net.minecraft.world.entity.monster.Shulker;',
    'import net.minecraft.entity.EntityEndermite;': 'import net.minecraft.world.entity.monster.Endermite;',
    'import net.minecraft.entity.EntityEvoker;': 'import net.minecraft.world.entity.monster.Evoker;',
    'import net.minecraft.entity.EntityVex;': 'import net.minecraft.world.entity.monster.Vex;',
    'import net.minecraft.entity.EntityVindicator;': 'import net.minecraft.world.entity.monster.Vindicator;',
    'import net.minecraft.entity.EntityPillager;': 'import net.minecraft.world.entity.monster.Pillager;',
    'import net.minecraft.entity.EntityRavager;': 'import net.minecraft.world.entity.monster.Ravager;',
    'import net.minecraft.entity.EntityIllusioner;': 'import net.minecraft.world.entity.monster.Illusioner;',
    'import net.minecraft.entity.EntityWitch;': 'import net.minecraft.world.entity.monster.Witch;',
    'import net.minecraft.entity.EntityWitherSkeleton;': 'import net.minecraft.world.entity.monster.WitherSkeleton;',
    'import net.minecraft.entity.EntityStray;': 'import net.minecraft.world.entity.monster.Stray;',
    'import net.minecraft.entity.EntityHusk;': 'import net.minecraft.world.entity.monster.Husk;',
    'import net.minecraft.entity.EntityDrowned;': 'import net.minecraft.world.entity.monster.Drowned;',
    'import net.minecraft.entity.EntityPhantom;': 'import net.minecraft.world.entity.monster.Phantom;',
    'import net.minecraft.entity.EntityPiglin;': 'import net.minecraft.world.entity.monster.piglin.Piglin;',
    'import net.minecraft.entity.EntityPiglinBrute;': 'import net.minecraft.world.entity.monster.piglin.PiglinBrute;',
    'import net.minecraft.entity.EntityZombifiedPiglin;': 'import net.minecraft.world.entity.monster.ZombifiedPiglin;',
    'import net.minecraft.entity.EntityHoglin;': 'import net.minecraft.world.entity.animal.hoglin.Hoglin;',
    'import net.minecraft.entity.EntityZoglin;': 'import net.minecraft.world.entity.animal.hoglin.Zoglin;',
    'import net.minecraft.entity.EntityStrider;': 'import net.minecraft.world.entity.animal.Strider;',
    'import net.minecraft.entity.EntityBlaze;': 'import net.minecraft.world.entity.monster.Blaze;',
    'import net.minecraft.entity.EntityCreeper;': 'import net.minecraft.world.entity.monster.Creeper;',
    'import net.minecraft.entity.EntityEnderman;': 'import net.minecraft.world.entity.monster.EnderMan;',
    'import net.minecraft.entity.EntityGhast;': 'import net.minecraft.world.entity.monster.Ghast;',
    'import net.minecraft.entity.EntityMagmaCube;': 'import net.minecraft.world.entity.monster.MagmaCube;',
    'import net.minecraft.entity.EntitySilverfish;': 'import net.minecraft.world.entity.monster.Silverfish;',
    'import net.minecraft.entity.EntitySkeleton;': 'import net.minecraft.world.entity.monster.Skeleton;',
    'import net.minecraft.entity.EntitySlime;': 'import net.minecraft.world.entity.monster.Slime;',
    'import net.minecraft.entity.EntitySpider;': 'import net.minecraft.world.entity.monster.Spider;',
    'import net.minecraft.entity.EntityZombie;': 'import net.minecraft.world.entity.monster.Zombie;',
    'import net.minecraft.entity.EntitySnowGolem;': 'import net.minecraft.world.entity.animal.SnowGolem;',
    'import net.minecraft.entity.EntityIronGolem;': 'import net.minecraft.world.entity.animal.IronGolem;',
    'import net.minecraft.entity.EntityGiantZombie;': 'import net.minecraft.world.entity.monster.Giant;',
    'import net.minecraft.entity.EntityWarden;': 'import net.minecraft.world.entity.monster.warden.Warden;',
    # Zusätzliche Methoden und Felder
    '.rotationYaw': '.getYRot()',
    '.rotationPitch': '.getXRot()',
    '.posX': '.getX()',
    '.posY': '.getY()',
    '.posZ': '.getZ()',
    '.motionX': '.getDeltaMovement().x',
    '.motionY': '.getDeltaMovement().y',
    '.motionZ': '.getDeltaMovement().z',
    '.onGround': '.onGround()',
    '.isBurning()': '.isOnFire()',
    '.isSneaking()': '.isCrouching()',
    '.isSprinting()': '.isSprinting()',
    '.isInWater()': '.isInWater()',
    '.isAirBorne': '.isAirborne',
    '.fallDistance': '.fallDistance',
    '.getHealth()': '.getHealth()',
    '.getMaxHealth()': '.getMaxHealth()',
    '.getArmorValue()': '.getArmorValue()',
    '.getActivePotionEffects()': '.getActiveEffects()',
    '.getHeldItemMainhand()': '.getMainHandItem()',
    '.getHeldItemOffhand()': '.getOffhandItem()',
    '.getHeldItem(EnumHand.MAIN_HAND)': '.getMainHandItem()',
    '.getHeldItem(EnumHand.OFF_HAND)': '.getOffhandItem()',
    '.getInventory()': '.getInventory()',
    '.getFoodStats()': '.getFoodData()',
    '.getTotalArmorValue()': '.getArmorValue()',
    '.getAbsorptionAmount()': '.getAbsorptionAmount()',
    '.getScore()': '.getScore()',
    '.getTeam()': '.getTeam()',
    '.getDisplayName()': '.getDisplayName()',
    '.getUUID()': '.getUUID()',
    '.getUniqueID()': '.getUUID()',
    '.getEntityId()': '.getId()',
    '.getEntityWorld()': '.level',
    '.getWorld()': '.level',
    '.getBlockPos()': '.blockPosition()',
    '.getPosition()': '.blockPosition()',
    '.getBlockMetadata()': '.getBlockState().getMeta()',
    '.getBlockState()': '.getBlockState()',
    '.getBlock()': '.getBlock()',
    '.getBlockType()': '.getBlock()',
    '.getBlockHardness()': '.getDestroySpeed()',
    '.getBlockResistance()': '.getExplosionResistance()',
    '.getBlockLightOpacity()': '.getLightBlock()',
    '.getBlockLightValue()': '.getLightEmission()',
    '.getBlockMaterial()': '.defaultBlockState().getMaterial()',
    '.getBlockSoundType()': '.getSoundType()',
    '.getBlockSlipperiness()': '.getFriction()',
    '.getBlockMapColor()': '.defaultBlockState().getMapColor()',
    '.getBlockRenderType()': '.getRenderShape()',
    '.getBlockRenderLayer()': '.getRenderLayer()',
    '.getBlockStateFromMeta': '.byMetadata',
    '.getMetaFromState': '.getMeta',
    '.getUnlocalizedName()': '.getDescriptionId()',
    '.getLocalizedName()': '.getName()',
    '.getRegistryName()': '.getRegistryName()',
    '.getTranslationKey()': '.getDescriptionId()',
    '.getCreativeTab()': '.getCreativeTab()',
    '.getSubBlocks': '.fillItemCategory',
    '.getPickBlock': '.getCloneItemStack',
    '.getHarvestLevel()': '.getHarvestLevel()',
    '.getHarvestTool()': '.getHarvestTool()',
    '.getEnchantability()': '.getEnchantmentValue()',
    '.getItemEnchantability()': '.getEnchantmentValue()',
    '.getItemUseAction()': '.getUseAnimation()',
    '.getItemUseDuration()': '.getUseDuration()',
    '.getItemStackLimit()': '.getMaxStackSize()',
    '.getItemDamage()': '.getDamageValue()',
    '.getMaxDamage()': '.getMaxDamage()',
    '.getStackSize()': '.getCount()',
    '.getNBTTagCompound()': '.getTag()',
    '.setTagCompound': '.setTag',
    '.hasTagCompound()': '.hasTag()',
    '.getTagCompound()': '.getTag()',
    '.getEnchantmentTagList()': '.getEnchantmentTags()',
    '.getEnchantmentLevel': '.getEnchantmentLevel',
    '.getEnchantmentId': '.getEnchantmentId',
    '.getEnchantmentName': '.getEnchantmentName',
    '.getEnchantmentByID': '.byId',
    '.getEnchantmentByLocation': '.byName',
    '.getEnchantmentList': '.getEnchantments',
    '.getEnchantmentLevel': '.getEnchantmentLevel',
    '.getEnchantmentId': '.getEnchantmentId',
    '.getEnchantmentName': '.getEnchantmentName',
    '.getEnchantmentByID': '.byId',
    '.getEnchantmentByLocation': '.byName',
    '.getEnchantmentList': '.getEnchantments',
    # Zusätzliche Enum-Mappings
    'EnumHand.MAIN_HAND': 'InteractionHand.MAIN_HAND',
    'EnumHand.OFF_HAND': 'InteractionHand.OFF_HAND',
    'EnumActionResult.SUCCESS': 'InteractionResult.SUCCESS',
    'EnumActionResult.PASS': 'InteractionResult.PASS',
    'EnumActionResult.FAIL': 'InteractionResult.FAIL',
    'EnumParticleTypes': 'ParticleOptions',
    'EnumCreatureType': 'MobCategory',
    'EnumDifficulty': 'Difficulty',
    'EnumChatType': 'ChatType',
    'EnumFacing.Axis': 'Direction.Axis',
    'EnumFacing.Plane': 'Direction.Plane',
    'EnumBlockRenderType': 'RenderShape',
    'EnumBlockRenderType.MODEL': 'RenderShape.MODEL',
    'EnumBlockRenderType.INVISIBLE': 'RenderShape.INVISIBLE',
    'EnumBlockRenderType.LIQUID': 'RenderShape.LIQUID',
    'EnumBlockRenderType.ENTITYBLOCK_ANIMATED': 'RenderShape.ENTITYBLOCK_ANIMATED',
    'EnumBlockRenderType.BLOCK': 'RenderShape.BLOCK',
    'EnumBlockRenderType.CUTOUT': 'RenderShape.CUTOUT',
    'EnumBlockRenderType.CUTOUT_MIPPED': 'RenderShape.CUTOUT_MIPPED',
    'EnumBlockRenderType.TRANSLUCENT': 'RenderShape.TRANSLUCENT',
    'import net.minecraft.client.multiplayer.WorldClient;': 'import net.minecraft.client.multiplayer.ClientLevel;',
    'import net.minecraft.client.multiplayer.ServerData;': 'import net.minecraft.client.multiplayer.ServerData;',
    'import net.minecraft.client.network.NetHandlerPlayClient;': 'import net.minecraft.client.multiplayer.ClientPacketListener;',
    'import net.minecraft.network.PacketBuffer;': 'import net.minecraft.network.FriendlyByteBuf;',
    'import net.minecraft.network.play.client.C01PacketChatMessage;': 'import net.minecraft.network.protocol.game.ServerboundChatPacket;',
    'import net.minecraft.network.play.server.S02PacketChat;': 'import net.minecraft.network.protocol.game.ClientboundSystemChatPacket;',
    'import net.minecraft.network.play.server.S03PacketTimeUpdate;': 'import net.minecraft.network.protocol.game.ClientboundSetTimePacket;',
    'import net.minecraft.network.play.server.S01PacketJoinGame;': 'import net.minecraft.network.protocol.game.ClientboundLoginPacket;',
    'import net.minecraft.network.play.server.S08PacketPlayerPosLook;': 'import net.minecraft.network.protocol.game.ClientboundPlayerPositionPacket;',
    'import net.minecraft.network.play.client.C03PacketPlayer;': 'import net.minecraft.network.protocol.game.ServerboundMovePlayerPacket;',
    'import net.minecraft.network.play.client.C0APacketAnimation;': 'import net.minecraft.network.protocol.game.ServerboundSwingPacket;',
    'import net.minecraft.network.play.server.S0BPacketAnimation;': 'import net.minecraft.network.protocol.game.ClientboundAnimatePacket;',
    'import net.minecraft.network.play.client.C0BPacketEntityAction;': 'import net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket;',
    'import net.minecraft.network.play.server.S0CPacketSpawnPlayer;': 'import net.minecraft.network.protocol.game.ClientboundAddPlayerPacket;',
    'import net.minecraft.network.play.server.S0FPacketSpawnMob;': 'import net.minecraft.network.protocol.game.ClientboundAddMobPacket;',
    'import net.minecraft.network.play.server.S10PacketSpawnPainting;': 'import net.minecraft.network.protocol.game.ClientboundAddPaintingPacket;',
    'import net.minecraft.network.play.server.S11PacketSpawnExperienceOrb;': 'import net.minecraft.network.protocol.game.ClientboundAddExperienceOrbPacket;',
    'import net.minecraft.network.play.server.S13PacketDestroyEntities;': 'import net.minecraft.network.protocol.game.ClientboundRemoveEntitiesPacket;',
    'import net.minecraft.network.play.server.S14PacketEntity;': 'import net.minecraft.network.protocol.game.ClientboundMoveEntityPacket;',
    'import net.minecraft.network.play.server.S18PacketEntityTeleport;': 'import net.minecraft.network.protocol.game.ClientboundTeleportEntityPacket;',
    'import net.minecraft.network.play.server.S19PacketEntityHeadLook;': 'import net.minecraft.network.protocol.game.ClientboundRotateHeadPacket;',
    'import net.minecraft.network.play.server.S1BPacketEntityAttach;': 'import net.minecraft.network.protocol.game.ClientboundSetEntityLinkPacket;',
    'import net.minecraft.network.play.server.S1CUpdateEntityNBT;': 'import net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket;',
    'import net.minecraft.network.play.server.S1DPacketEntityEffect;': 'import net.minecraft.network.protocol.game.ClientboundUpdateMobEffectPacket;',
    'import net.minecraft.network.play.server.S1EPacketRemoveEntityEffect;': 'import net.minecraft.network.protocol.game.ClientboundRemoveMobEffectPacket;',
    'import net.minecraft.network.play.server.S20PacketEntityProperties;': 'import net.minecraft.network.protocol.game.ClientboundUpdateAttributesPacket;',
    'import net.minecraft.network.play.server.S21PacketChunkData;': 'import net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket;',
    'import net.minecraft.network.play.server.S22PacketMultiBlockChange;': 'import net.minecraft.network.protocol.game.ClientboundSectionBlocksUpdatePacket;',
    'import net.minecraft.network.play.server.S23PacketBlockChange;': 'import net.minecraft.network.protocol.game.ClientboundBlockUpdatePacket;',
    'import net.minecraft.network.play.server.S24PacketBlockAction;': 'import net.minecraft.network.protocol.game.ClientboundBlockEventPacket;',
    'import net.minecraft.network.play.server.S25PacketBlockBreakAnim;': 'import net.minecraft.network.protocol.game.ClientboundBlockDestructionPacket;',
    'import net.minecraft.network.play.server.S26PacketMapChunkBulk;': 'import net.minecraft.network.protocol.game.ClientboundChunksBiomesPacket;',
    'import net.minecraft.network.play.server.S27PacketExplosion;': 'import net.minecraft.network.protocol.game.ClientboundExplodePacket;',
    'import net.minecraft.network.play.server.S28PacketEffect;': 'import net.minecraft.network.protocol.game.ClientboundLevelEventPacket;',
    'import net.minecraft.network.play.server.S29PacketSoundEffect;': 'import net.minecraft.network.protocol.game.ClientboundSoundPacket;',
    'import net.minecraft.network.play.server.S2APacketParticles;': 'import net.minecraft.network.protocol.game.ClientboundLevelParticlesPacket;',
    'import net.minecraft.network.play.server.S2BPacketChangeGameState;': 'import net.minecraft.network.protocol.game.ClientboundGameEventPacket;',
    'import net.minecraft.network.play.server.S2CPacketSpawnGlobalEntity;': 'import net.minecraft.network.protocol.game.ClientboundAddGlobalEntityPacket;',
    'import net.minecraft.network.play.server.S2DPacketOpenWindow;': 'import net.minecraft.network.protocol.game.ClientboundOpenScreenPacket;',
    'import net.minecraft.network.play.server.S2EPacketCloseWindow;': 'import net.minecraft.network.protocol.game.ClientboundContainerClosePacket;',
    'import net.minecraft.network.play.server.S2FPacketSetSlot;': 'import net.minecraft.network.protocol.game.ClientboundContainerSetSlotPacket;',
    'import net.minecraft.network.play.server.S30PacketWindowItems;': 'import net.minecraft.network.protocol.game.ClientboundContainerSetContentPacket;',
    'import net.minecraft.network.play.server.S31PacketWindowProperty;': 'import net.minecraft.network.protocol.game.ClientboundContainerSetDataPacket;',
    'import net.minecraft.network.play.server.S32PacketConfirmTransaction;': 'import net.minecraft.network.protocol.game.ClientboundContainerAckPacket;',
    'import net.minecraft.network.play.server.S33PacketUpdateSign;': 'import net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket;',
    'import net.minecraft.network.play.server.S34PacketMaps;': 'import net.minecraft.network.protocol.game.ClientboundMapItemDataPacket;',
    'import net.minecraft.network.play.server.S35PacketUpdateTileEntity;': 'import net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket;',
    'import net.minecraft.network.play.server.S36PacketSignEditorOpen;': 'import net.minecraft.network.protocol.game.ClientboundOpenSignEditorPacket;',
    'import net.minecraft.network.play.server.S37PacketStatistics;': 'import net.minecraft.network.protocol.game.ClientboundAwardStatsPacket;',
    'import net.minecraft.network.play.server.S38PacketPlayerListItem;': 'import net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket;',
    'import net.minecraft.network.play.server.S39PacketPlayerAbilities;': 'import net.minecraft.network.protocol.game.ClientboundPlayerAbilitiesPacket;',
    'import net.minecraft.network.play.server.S3APacketTabComplete;': 'import net.minecraft.network.protocol.game.ClientboundCommandSuggestionsPacket;',
    'import net.minecraft.network.play.server.S3BPacketScoreboardObjective;': 'import net.minecraft.network.protocol.game.ClientboundSetObjectivePacket;',
    'import net.minecraft.network.play.server.S3CPacketUpdateScore;': 'import net.minecraft.network.protocol.game.ClientboundSetScorePacket;',
    'import net.minecraft.network.play.server.S3DPacketDisplayScoreboard;': 'import net.minecraft.network.protocol.game.ClientboundSetDisplayObjectivePacket;',
    'import net.minecraft.network.play.server.S3EPacketTeams;': 'import net.minecraft.network.protocol.game.ClientboundSetPlayerTeamPacket;',
    'import net.minecraft.network.play.server.S3FPacketCustomPayload;': 'import net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket;',
    'import net.minecraft.network.play.server.S40PacketDisconnect;': 'import net.minecraft.network.protocol.game.ClientboundDisconnectPacket;',
    'import net.minecraft.network.play.server.S41PacketServerDifficulty;': 'import net.minecraft.network.protocol.game.ClientboundChangeDifficultyPacket;',
    'import net.minecraft.network.play.server.S42PacketCombatEvent;': 'import net.minecraft.network.protocol.game.ClientboundPlayerCombatKillPacket;',
    'import net.minecraft.network.play.server.S43PacketCamera;': 'import net.minecraft.network.protocol.game.ClientboundSetCameraPacket;',
    'import net.minecraft.network.play.server.S44PacketWorldBorder;': 'import net.minecraft.network.protocol.game.ClientboundInitializeBorderPacket;',
    'import net.minecraft.network.play.server.S45PacketTitle;': 'import net.minecraft.network.protocol.game.ClientboundSetTitlesPacket;',
    'import net.minecraft.network.play.server.S46PacketSetCompressionLevel;': 'import net.minecraft.network.protocol.common.ClientboundSetCompressionPacket;',
    'import net.minecraft.network.play.server.S47PacketPlayerListHeaderFooter;': 'import net.minecraft.network.protocol.game.ClientboundTabListPacket;',
    'import net.minecraft.network.play.server.S48PacketResourcePackSend;': 'import net.minecraft.network.protocol.game.ClientboundResourcePackPacket;',
    'import net.minecraft.network.play.server.S49PacketUpdateEntityNBT;': 'import net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket;',
    'import net.minecraft.client.settings.GameSettings;': 'import net.minecraft.client.Options;',
    'import net.minecraft.client.settings.KeyBinding;': 'import net.minecraft.client.KeyMapping;',
    'import net.minecraft.client.resources.model.ModelResourceLocation;': 'import net.minecraft.client.resources.model.ModelResourceLocation;',
    'import net.minecraft.client.renderer.entity.RenderManager;': 'import net.minecraft.client.renderer.entity.EntityRenderDispatcher;',
    'import net.minecraft.client.renderer.entity.RenderPlayer;': 'import net.minecraft.client.renderer.entity.PlayerRenderer;',
    'import net.minecraft.client.renderer.entity.RenderLivingBase;': 'import net.minecraft.client.renderer.entity.LivingEntityRenderer;',
    'import net.minecraft.client.renderer.entity.Render;': 'import net.minecraft.client.renderer.entity.EntityRenderer;',
    'import net.minecraft.client.renderer.entity.RenderItem;': 'import net.minecraft.client.renderer.entity.ItemRenderer;',
    'import net.minecraft.client.renderer.entity.RenderSnowball;': 'import net.minecraft.client.renderer.entity.ThrownItemRenderer;',
    'import net.minecraft.client.renderer.entity.RenderBoat;': 'import net.minecraft.client.renderer.entity.BoatRenderer;',
    'import net.minecraft.client.renderer.entity.RenderMinecart;': 'import net.minecraft.client.renderer.entity.MinecartRenderer;',
    'import net.minecraft.client.renderer.entity.RenderArmorStand;': 'import net.minecraft.client.renderer.entity.ArmorStandRenderer;',
    'import net.minecraft.client.renderer.entity.RenderPainting;': 'import net.minecraft.client.renderer.entity.PaintingRenderer;',
    'import net.minecraft.client.renderer.entity.RenderItemFrame;': 'import net.minecraft.client.renderer.entity.ItemFrameRenderer;',
    'import net.minecraft.client.renderer.entity.RenderDragon;': 'import net.minecraft.client.renderer.entity.EnderDragonRenderer;',
    'import net.minecraft.client.renderer.entity.RenderWither;': 'import net.minecraft.client.renderer.entity.WitherBossRenderer;',
    'import net.minecraft.client.renderer.entity.RenderArrow;': 'import net.minecraft.client.renderer.entity.ArrowRenderer;',
    'import net.minecraft.client.renderer.entity.RenderSnowball;': 'import net.minecraft.client.renderer.entity.SnowballRenderer;',
    'import net.minecraft.client.renderer.entity.RenderPotion;': 'import net.minecraft.client.renderer.entity.ThrownPotionRenderer;',
    'import net.minecraft.client.renderer.entity.RenderEnderPearl;': 'import net.minecraft.client.renderer.entity.ThrownEnderpearlRenderer;',
    'import net.minecraft.client.renderer.entity.RenderFireball;': 'import net.minecraft.client.renderer.entity.AbstractHurtingProjectileRenderer;',
    'import net.minecraft.client.renderer.entity.RenderSmallFireball;': 'import net.minecraft.client.renderer.entity.SmallFireballRenderer;',
    'import net.minecraft.client.renderer.entity.RenderLargeFireball;': 'import net.minecraft.client.renderer.entity.LargeFireballRenderer;',
    'import net.minecraft.client.renderer.entity.RenderEgg;': 'import net.minecraft.client.renderer.entity.ThrownEggRenderer;',
    'import net.minecraft.client.renderer.entity.RenderFishHook;': 'import net.minecraft.client.renderer.entity.FishingBobberRenderer;',
    'import net.minecraft.client.renderer.entity.RenderBlaze;': 'import net.minecraft.client.renderer.entity.BlazeRenderer;',
    'import net.minecraft.client.renderer.entity.RenderCreeper;': 'import net.minecraft.client.renderer.entity.CreeperRenderer;',
    'import net.minecraft.client.renderer.entity.RenderEnderman;': 'import net.minecraft.client.renderer.entity.EnderManRenderer;',
    'import net.minecraft.client.renderer.entity.RenderGhast;': 'import net.minecraft.client.renderer.entity.GhastRenderer;',
    'import net.minecraft.client.renderer.entity.RenderMagmaCube;': 'import net.minecraft.client.renderer.entity.MagmaCubeRenderer;',
    'import net.minecraft.client.renderer.entity.RenderSilverfish;': 'import net.minecraft.client.renderer.entity.SilverfishRenderer;',
    'import net.minecraft.client.renderer.entity.RenderSkeleton;': 'import net.minecraft.client.renderer.entity.SkeletonRenderer;',
    'import net.minecraft.client.renderer.entity.RenderSlime;': 'import net.minecraft.client.renderer.entity.SlimeRenderer;',
    'import net.minecraft.client.renderer.entity.RenderSpider;': 'import net.minecraft.client.renderer.entity.SpiderRenderer;',
    'import net.minecraft.client.renderer.entity.RenderZombie;': 'import net.minecraft.client.renderer.entity.ZombieRenderer;',
    'import net.minecraft.client.renderer.entity.RenderGiantZombie;': 'import net.minecraft.client.renderer.entity.GiantRenderer;',
    'import net.minecraft.client.renderer.entity.RenderWarden;': 'import net.minecraft.client.renderer.entity.WardenRenderer;',
    'import net.minecraft.client.renderer.entity.RenderGuardian;': 'import net.minecraft.client.renderer.entity.GuardianRenderer;',
    'import net.minecraft.client.renderer.entity.RenderElderGuardian;': 'import net.minecraft.client.renderer.entity.ElderGuardianRenderer;',
    'import net.minecraft.client.renderer.entity.RenderShulker;': 'import net.minecraft.client.renderer.entity.ShulkerRenderer;',
    'import net.minecraft.client.renderer.entity.RenderEndermite;': 'import net.minecraft.client.renderer.entity.EndermiteRenderer;',
    'import net.minecraft.client.renderer.entity.RenderEvoker;': 'import net.minecraft.client.renderer.entity.EvokerRenderer;',
    'import net.minecraft.client.renderer.entity.RenderVex;': 'import net.minecraft.client.renderer.entity.VexRenderer;',
    'import net.minecraft.client.renderer.entity.RenderVindicator;': 'import net.minecraft.client.renderer.entity.VindicatorRenderer;',
    'import net.minecraft.client.renderer.entity.RenderPillager;': 'import net.minecraft.client.renderer.entity.PillagerRenderer;',
    'import net.minecraft.client.renderer.entity.RenderRavager;': 'import net.minecraft.client.renderer.entity.RavagerRenderer;',
    'import net.minecraft.client.renderer.entity.RenderIllusioner;': 'import net.minecraft.client.renderer.entity.IllusionerRenderer;',
    'import net.minecraft.client.renderer.entity.RenderWitch;': 'import net.minecraft.client.renderer.entity.WitchRenderer;',
    'import net.minecraft.client.renderer.entity.RenderWitherSkeleton;': 'import net.minecraft.client.renderer.entity.WitherSkeletonRenderer;',
    'import net.minecraft.client.renderer.entity.RenderStray;': 'import net.minecraft.client.renderer.entity.StrayRenderer;',
    'import net.minecraft.client.renderer.entity.RenderHusk;': 'import net.minecraft.client.renderer.entity.HuskRenderer;',
    'import net.minecraft.client.renderer.entity.RenderDrowned;': 'import net.minecraft.client.renderer.entity.DrownedRenderer;',
    'import net.minecraft.client.renderer.entity.RenderPhantom;': 'import net.minecraft.client.renderer.entity.PhantomRenderer;',
    'import net.minecraft.client.renderer.entity.RenderPiglin;': 'import net.minecraft.client.renderer.entity.PiglinRenderer;',
    'import net.minecraft.client.renderer.entity.RenderPiglinBrute;': 'import net.minecraft.client.renderer.entity.PiglinBruteRenderer;',
    'import net.minecraft.client.renderer.entity.RenderZombifiedPiglin;': 'import net.minecraft.client.renderer.entity.ZombifiedPiglinRenderer;',
    'import net.minecraft.client.renderer.entity.RenderHoglin;': 'import net.minecraft.client.renderer.entity.HoglinRenderer;',
    'import net.minecraft.client.renderer.entity.RenderZoglin;': 'import net.minecraft.client.renderer.entity.ZoglinRenderer;',
    'import net.minecraft.client.renderer.entity.RenderStrider;': 'import net.minecraft.client.renderer.entity.StriderRenderer;',
    # Zusätzliche Typnamen
    'EntityPlayerSP': 'LocalPlayer',
    'WorldClient': 'ClientLevel',
    'GameSettings': 'Options',
    'KeyBinding': 'KeyMapping',
    'ScaledResolution': 'Window',
    'IChatComponent': 'Component',
    'ChatComponentText': 'TextComponent',
    'ChatComponentTranslation': 'TranslatableComponent',
    'EnumPlayerModelParts': 'PlayerModelPart',
    'EnumHandSide': 'HumanoidArm',
    'EnumParticleTypes': 'ParticleOptions',
    'EnumCreatureType': 'MobCategory',
    'EnumDifficulty': 'Difficulty',
    'EnumChatType': 'ChatType',
    'EnumFacing.Axis': 'Direction.Axis',
    'EnumFacing.Plane': 'Direction.Plane',
    'EnumBlockRenderType': 'RenderShape',
    'EnumBlockRenderType.MODEL': 'RenderShape.MODEL',
    'EnumBlockRenderType.INVISIBLE': 'RenderShape.INVISIBLE',
    'EnumBlockRenderType.LIQUID': 'RenderShape.LIQUID',
    # Methoden und Felder (weitere Beispiele)
    '.getDisplayName()': '.getName()',
    '.getUnformattedText()': '.getString()',
    '.getFormattedText()': '.getString()',
    '.getChatStyle()': '.getStyle()',
    '.setChatStyle': '.withStyle',
    '.appendSibling': '.append',
    '.appendText': '.append',
    '.getUnformattedComponentText()': '.getString()',
    '.getHoverEvent()': '.getStyle().getHoverEvent()',
    '.getClickEvent()': '.getStyle().getClickEvent()',
    '.getSiblings()': '.getSiblings()',
    '.getChatComponentText()': '.getString()',
    '.getChatComponentTranslation()': '.getString()',
    '.getChatComponentStyle()': '.getStyle()',
    '.getChatComponentSiblings()': '.getSiblings()',
    '.getChatComponentUnformattedText()': '.getString()',
    '.getChatComponentFormattedText()': '.getString()',
    '.getChatComponentUnformattedComponentText()': '.getString()',
    '.getChatComponentHoverEvent()': '.getStyle().getHoverEvent()',
    '.getChatComponentClickEvent()': '.getStyle().getClickEvent()',
    '.getChatComponentChatStyle()': '.getStyle()',
    '.getChatComponentChatModifier()': '.getStyle()',
    '.getChatComponentChatModifierSiblings()': '.getSiblings()',
    '.getChatComponentChatModifierUnformattedText()': '.getString()',
    '.getChatComponentChatModifierFormattedText()': '.getString()',
    '.getChatComponentChatModifierUnformattedComponentText()': '.getString()',
    '.getChatComponentChatModifierHoverEvent()': '.getStyle().getHoverEvent()',
    '.getChatComponentChatModifierClickEvent()': '.getStyle().getClickEvent()',
    '.getChatComponentChatModifierChatStyle()': '.getStyle()',
    '.getChatComponentChatModifierChatModifier()': '.getStyle()',
    '.getChatComponentChatModifierChatModifierSiblings()': '.getSiblings()',
    # Window/Screen
    '.getScaledWidth()': '.getGuiScaledWidth()',
    '.getScaledHeight()': '.getGuiScaledHeight()',
    '.width': '.width',
    '.height': '.height',
    '.mc': '.minecraft',
    '.thePlayer': '.player',
    '.theWorld': '.level',
    '.playerController': '.gameMode',
    '.renderEngine': '.textureManager',
    '.fontRendererObj': '.font',
    '.currentScreen': '.screen',
    '.displayWidth': '.getWindow().getWidth()',
    '.displayHeight': '.getWindow().getHeight()',
    '.gameSettings': '.options',
    '.rightClickDelayTimer': '.rightClickDelay',
    '.objectMouseOver': '.hitResult',
    '.inGameHasFocus': '.isWindowActive()',
    '.isSingleplayer()': '.hasSingleplayerServer()',
    '.isIntegratedServerRunning()': '.hasSingleplayerServer()',
    '.isMultiplayerWorld()': '.isMultiplayer()',
    '.getSession()': '.getUser()',
    '.getSession().getUsername()': '.getUser().getName()',
    '.getSession().getPlayerID()': '.getUser().getUuid()',
    '.getSession().getToken()': '.getUser().getAccessToken()',
    '.getSession().getSessionID()': '.getUser().getSessionId()',
    '.getSession().getProfile()': '.getUser().getProfile()',
    '.getSession().getProperties()': '.getUser().getProperties()',
    '.getSession().getType()': '.getUser().getType()',
    '.getSession().getUserType()': '.getUser().getType()',
    '.getSession().getUserProperties()': '.getUser().getProperties()',
    '.getSession().getUserId()': '.getUser().getUuid()',
    '.getSession().getUserName()': '.getUser().getName()',
    '.getSession().getUserUuid()': '.getUser().getUuid()',
    '.getSession().getUserAccessToken()': '.getUser().getAccessToken()',
    '.getSession().getUserSessionId()': '.getUser().getSessionId()',
    '.getSession().getUserProfile()': '.getUser().getProfile()',
    '.getSession().getUserProperties()': '.getUser().getProperties()',
    '.getSession().getUserType()': '.getUser().getType()',
    '.getSession().getUserUserType()': '.getUser().getType()',
    '.getSession().getUserUserProperties()': '.getUser().getProperties()',
    '.getSession().getUserUserId()': '.getUser().getUuid()',
    '.getSession().getUserUserName()': '.getUser().getName()',
    '.getSession().getUserUserUuid()': '.getUser().getUuid()',
    '.getSession().getUserUserAccessToken()': '.getUser().getAccessToken()',
    '.getSession().getUserUserSessionId()': '.getUser().getSessionId()',
    '.getSession().getUserUserProfile()': '.getUser().getProfile()',
    '.getSession().getUserUserProperties()': '.getUser().getProperties()',
    '.getSession().getUserUserType()': '.getUser().getType()',
    '.getSession().getUserUserUserType()': '.getUser().getType()',
    '.getSession().getUserUserUserProperties()': '.getUser().getProperties()',
    '.getSession().getUserUserUserId()': '.getUser().getUuid()',
    '.getSession().getUserUserUserName()': '.getUser().getName()',
    '.getSession().getUserUserUserUuid()': '.getUser().getUuid()',
    '.getSession().getUserUserUserAccessToken()': '.getUser().getAccessToken()',
    '.getSession().getUserUserUserSessionId()': '.getUser().getSessionId()',
    '.getSession().getUserUserUserProfile()': '.getUser().getProfile()',
    '.getSession().getUserUserUserProperties()': '.getUser().getProperties()',
    '.getSession().getUserUserUserType()': '.getUser().getType()',
})

def should_replace_symbol(line, old, new):
    # Nicht in Importen aus eaglercraft ersetzen
    if line.strip().startswith("import ") and "eaglercraft" in line:
        return False
    # Nicht in Klassendeklarationen ersetzen
    if line.strip().startswith("public class") or line.strip().startswith("class "):
        return False
    # Nicht in Interface-Deklarationen ersetzen
    if line.strip().startswith("public interface") or line.strip().startswith("interface "):
        return False
    # Nicht in Enum-Deklarationen ersetzen
    if line.strip().startswith("public enum") or line.strip().startswith("enum "):
        return False
    # Imports werden immer ersetzt, außer eaglercraft
    if line.strip().startswith("import "):
        return True
    # Sonst nur ersetzen, wenn das Symbol als Wort vorkommt (kein Teilwort)
    import re
    return re.search(r'\b' + re.escape(old) + r'\b', line) is not None

def replace_in_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    new_lines = []
    for line in lines:
        new_line = line
        for old, new in REPLACEMENTS.items():
            if should_replace_symbol(line, old, new):
                import re
                # Nur ganzes Wort ersetzen
                new_line = re.sub(r'\b' + re.escape(old) + r'\b', new, new_line)
        new_lines.append(new_line)
    if new_lines != lines:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.writelines(new_lines)
        print(f"Replaced in: {filepath}")

def process_directory(root_dir):
    for dirpath, _, filenames in os.walk(root_dir):
        for filename in filenames:
            if filename.endswith('.java'):
                replace_in_file(os.path.join(dirpath, filename))

if __name__ == "__main__":
    # Passe den Pfad ggf. an!
    process_directory(".")